### PR TITLE
Python 3 Compatiable Yum

### PR DESCRIPTION
**Pull request by ralic**

### CODE REVIEW

**Comment by anatol** [comment]
It is great to see this update. Any ETA on when it can be applied to `master` branch?

**Comment by j-mracek** [comment]
For anyone who has an interest in Python 2/3 compatible software management tool I have a good news. There is DNF. It is fork of YUM that is maintained and part of many distribution including Fedora, Centos, RHEL, OpenSuse, Mageila, ... . YUM project is EOL, therefore merging this PR with knowledge that it is not maintained anyway is something that I would like to avoid. I have a plan to close the pull request.

**Comment by ralic** [comment]
Many installation scripts are still depending on yum. I wonder if you would like to make a last test check after this merge.

**Comment by j-mracek** [comment]
I am really sorry but I do recommend to everyone to port py2 YUM scripts to Python3 DNF scripts.
The reasons are:
1. There is no plan to release YUM with PY3 support. Yum was already removed from Fedora31 therefore it dies completely in Fedora with Fedora 30 EOL .
2. Python 3 compatible YUM code will have many new issues but no one will fix them

**Pull request closed without merging**
