### PR TITLE
Created the stuff needed for a pip package and replaced async with asyncr to support python 3 where async is a keyword

### PR DESCRIPTION
**Pull request by KOLANICH**

### CODE REVIEW

**Comment by j-mracek** [comment]
Due to removal of `YUM` from Fedora and existence of replacement - `DNF` (fork of `YUM` that is maintained), I believe that support of an alternative distribution is something that is going against long term plan for the `YUM` project (EOL).

**Comment by KOLANICH** [comment]
In fact I have fixed this (and some other packages) before I got known about dnf.

**Comment by Conan-Kudo** [comment]
Moreover, this codebase is not Python 3 compatible. If you want to make _this_ work on Python 3, you'd need to do a fair bit of work...

**Comment by KOLANICH** [comment]
>Moreover, this codebase is not Python 3 compatible. If you want to make this work on Python 3, you'd need to do a fair bit of work...

For porting to python3 automatically `use_2to3 = True` in `setup.cfg` should do the most of job. In fact I haven't tried if this actually works, only tried if this installs with pip and imports. As soon I have discovered that dnf (and the most importantly libdnf and hawkey) exists I have shifted all the efforts to them.

**Comment by j-mracek** [comment]
I am closing it due to no plans for `yum` with Python3. Oh sorry I will close it when I will get proper rights.

**Pull request closed without merging**
