### PR TITLE
Print a disk usage summary on "yum clean all". BZ 1481220

### PR DESCRIPTION
**Pull request by dmnks**
Replace the confusing "rm -rf" hint with actual info on how much data is
still left behind in the cache.

This commit also removes the "Cleaning up everything" message since
"everything" was often understood by users as "everything ever cached".

### CODE REVIEW

**Comment by james-antill** [comment]
I think the idea is good, although I've found one of the biggest problems is previous releasever caches (so you are on f28 but f27 has a bunch of data in it and it'll never get cleaned) and this won't be obvious from the current output.

**Comment by dmnks** [comment]
Right, I was aware of that and tried to address it. However, I didn't want the message to be too verbose.

The idea was to give the user some sort of warning that some data is still left in the cache even after the cleanup. By printing the actual space usage and pointing out how much is consumed by disabled or orphaned repos, including any other releasever values, would hopefully make it clear that all this stuff isn't cleaned up automatically, while providing useful info on how much space can still be reclaimed.

The message looks like this:
```
Disk usage of cache after this cleanup (all distro releases):
0 B    enabled repos
109 k  disabled repos
0 B    orphaned repos (no config)
109 k  total
```

I was hoping that including `all distro releases` would make it clear that, if some data is still left (esp. for enabled repos), it's probably due to other releases (the reason I didn't use "$releasever" in the message is that casual users might not know what $releasever is, so better keep it simple and clear).

Printing an additional line with something like "Cleaning enabled repos for current releasever (27)" might not be a bad idea, however that is true for any "yum clean" invocation (not just "all"), so we would then have to print it with any of the other options as well. And it would make the output more verbose, again.

**Comment by dmnks** [comment]
Just in case it wasn't obvious from the code or the above comment, the summary table really includes data for any other cached releasevers, too (it traverses the cachedir recursively by treating $releasever as a wildcard, basically).

**Comment by dmnks** [comment]
Just pushed a reworked version, hopefully more user-friendly.

**Comment by j-mracek** [comment]
What about to add path here: "Disk usage of cache at '<path>' after this cleanup (all distro releases):" Then it can be easily applied "rm -rf <path>"

**Comment by dmnks** [comment]
> What about to add path here: "Disk usage of cache at '' after this cleanup (all distro releases):" Then it can be easily applied "rm -rf "

It's actually [there](https://github.com/rpm-software-management/yum/pull/77/commits/815f7557bbdee5afa9ae6d647b238d2818ec5cb8#diff-b15131236e6c2c6fbd87ed7939055ddeR1795) (in --verbose mode).

Please note the previous comment where you saw the message is outdated; I have reworked the patch a little bit since then.

**Comment by dmnks** [comment]
For reference, this is the new behavior:

```
# yum makecache
# yum makecache --releasever=7.5
# yum-config-manager --disable optional
# yum clean all
Cleaning repos: base
Other repos take up 160 M of disk space (use --verbose for details)
# yum clean all --verbose
Config time: 0.004
Yum version: 3.4.3
Cleaning repos: base
Operating on /var/cache/yum/x86_64/7Server (see CLEAN OPTIONS in yum(8) for details)
Disk usage of /var/cache/yum/*/* after cleanup:
59 M   enabled repos:
  59 M   /var/cache/yum/x86_64/7.5/base
100 M  disabled repos:
  50 M   /var/cache/yum/x86_64/7Server/optional
  50 M   /var/cache/yum/x86_64/7.5/optional
0      untracked repos
100    other data:
  50     /var/cache/yum/x86_64/7Server/timedhosts
  50     /var/cache/yum/x86_64/7.5/timedhosts
160 M  total
```

**Pull request merged**
