### PR TITLE
Add podman-based development support

### PR DESCRIPTION
**Pull request by dmnks**
Improves a developer's (my) life :)

### CODE REVIEW

**Comment by dmnks** [comment]
@james-antill Hey, I don't feel like merging this without having involved another pair of eyes, so I'd like to ask you for a quick glance before I do. Note that this is just an upstream change that's not intended for Fedora or RHEL. Thanks!

**Comment by dmnks** [comment]
I have a few additional ideas how to improve this, closing for now.

**Review by Conan-Kudo — APPROVED** [review]
I'm not @james-antill, but the changes look good to me.

**Comment by dmnks** [comment]
I suppose it won't do any harm to have this merged, so I'll just do that :)

**Pull request merged**
