### PR TITLE
skipbroken: don't remove old pkg on dep problems

### PR DESCRIPTION
**Pull request by dmnks**
This fixes a typo in f8c15289427c24130a7cdf5bf2f9eb524fc3fa19 that
caused the patch to be ineffective.  The problem was that we were
storing a txmbr in TransactionMember.depends_on later in the function,
while we expect package objects there.

### CODE REVIEW

**Comment by dmnks** [comment]
Found this by accident when working on bug 1306142.

**Comment by james-antill** [comment]
That's not a full fix. "m" there is whatever is randomly last in the for loop above it, which might not even be the same package name. We need to store one of the new txmbr's as the value part of found, and use that (or something similar).

**Comment by dmnks** [comment]
Nice catch, thanks. It seems that doing it the way you describe would make sense, however we don't know in advance which of the new txmbrs would fail. Example:

```
installonly_limit = 3
rpmdb = [kernel-1, kernel-2, kernel-3]
yum install kernel-4 kernel-5 --skip-broken
ts = [kernel-4(i), kernel-5(i)]
apply_installonly_limit
    add kernel-1 and kernel-2 erasures to ts
    make kernel-1 a dependency of kernel-4  # this is the patch
ts = [kernel-1(e), kernel-2(e), kernel-4(i), kernel-5(i)]
apply_skipbroken
    oops, kernel-4 can't be installed (e.g. some deps not satisfied),
    so remove it from ts, and also its dependencies
ts = [kernel-2(e), kernel-5(i)]
```

So far so good. However:

```
...
apply_skipbroken
    oops, kernel-5 can't be installed (e.g. some deps not satisfied),
    so remove it from ts, and also its dependencies
ts = [kernel-1(e), kernel-2(e), kernel-4(i)]
```

Which would result in 2 kernels being removed and only 1 installed. How should we handle this?

**Comment by dmnks** [comment]
Note that this would work when only one new txmbr is being installed (most common scenario probably), which is what the original patch was only supposed to handle, I guess.  So if that's sufficient, we could solve this by only doing the dependency setting when there's one such new txmbr, and don't do it at all if there are more.

**Comment by james-antill** [comment]
I'm tempted to say it's a feature, the other way would be to make the erasures a dep. of all installing kernels ... so the failure would be going over the installonly limit. We could also rerun installonly logic after skip-broken, and everything will work correctly.

I'm not that bothered about just leaving it though, installing multiple installonly things is not a common thing to do ... and then you need skip-broken and a failure on top of that.

**Comment by dmnks** [comment]
> I'm not that bothered about just leaving it though, installing multiple installonly things is not a common thing to do ... and then you need skip-broken and a failure on top of that.

Agreed, let's keep it simple. I'll prepare the new patch shortly.

**Comment by dmnks** [comment]
Patch updated.

**Pull request merged**
