### PR TITLE
yum-cron: make sure self.output is fully unicode. BZ 1425776

### LINKED ISSUE #97: yum-cron Unicode Decode Error on locale de_DE.utf8
yum-cron sends a stacktrace via email if the output contains special characters (e.g. missing key for an rpm:

```
Warnung: /var/cache/yum/x86_64/7/ius/packages/php72u-mysqlnd-7.2.21-1.el7.ius.x86_64.rpm: Header V4 RSA/SHA256 Signature, Schlüssel-ID 4b274df2: NOKEY
GPG-Schlüssel 0x4B274DF2 importieren:
 Benutzerkennung     : "IUS (7) <dev@ius.io>"
 Fingerabdruck: c958 7a09 a11f d706 4f0c a0f4 e558 0725 4b27 4df2
 Paket    : ius-release-2-1.el7.ius.noarch (@ius)
 Von       : /etc/pki/rpm-gpg/RPM-GPG-KEY-IUS-7
Traceback (most recent call last):
  File "/usr/sbin/yum-cron", line 729, in <module>
    main()
  File "/usr/sbin/yum-cron", line 726, in main
    base.updatesCheck()
  File "/usr/sbin/yum-cron", line 649, in updatesCheck
    self.installUpdates(self.opts.update_messages)
  File "/usr/sbin/yum-cron", line 577, in installUpdates
    self.emitUpdateFailed(errmsg)
  File "/usr/sbin/yum-cron", line 708, in emitUpdateFailed
    map(lambda x: x.updatesFailed(errmsg), self.emitters)
  File "/usr/sbin/yum-cron", line 708, in <lambda>
    map(lambda x: x.updatesFailed(errmsg), self.emitters)
  File "/usr/sbin/yum-cron", line 136, in updatesFailed
    self.sendMessages()
  File "/usr/sbin/yum-cron", line 268, in sendMessages
    print "".join(self.output)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 81: ordinal not in range(128)
```

relevant word is probably "Schlüssel", and it traces back to the following line:

https://github.com/rpm-software-management/yum/blob/594b49a1da7c98c589dd3bde0f9397d898ecefa5/yum-cron/yum-cron.py#L268

a most likely similar bug is also a few lines up, and documented with a patch in rh-bugzilla.

https://bugzilla.redhat.com/show_bug.cgi?id=1425776

### PR DESCRIPTION
**Pull request by dmnks**
Closes #97.

### CODE REVIEW

**Review by deed02392 — CHANGES_REQUESTED** [review]
Thanks for PR, can you explain the calls to `sendMessages()`? I believe this can cause multiple e-mails to get sent and also not sure if they are necessary.

**Comment by dmnks** [comment]
They are calling the parent method of `UpdateEmitter` where we do the conversion of `self.output` to unicode. Why do you think they could produce multiple emails?

**Review by deed02392 — APPROVED** [review]
Ah, don't think I appreciated they were just calling the method on the abstract class where you've implemented the decoding. My bad. I've double checked everything and it looks good to me.

**Comment by dmnks** [comment]
No problem, thanks for the feedback!

**Pull request merged**
